### PCA - Wine

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
wine = load_wine()
wine_std = StandardScaler().fit_transform(wine.data)
wine_std.shape

(178, 13)

##### 1. 차원 축소
- 13 차원을 2, 4, 6 차원으로 축소

In [4]:
from sklearn.decomposition import PCA

- 2차원

In [5]:
pca2 = PCA(n_components=2)
wine_pca2 = pca2.fit_transform(wine_std)
wine_pca2[:3]

array([[ 3.31675081, -1.44346263],
       [ 2.20946492,  0.33339289],
       [ 2.51674015, -1.0311513 ]])

In [6]:
pca2.explained_variance_ratio_, sum(pca2.explained_variance_ratio_)

(array([0.36198848, 0.1920749 ]), 0.554063383569353)

- 4차원

In [7]:
pca4 = PCA(n_components=4)
wine_pca4 = pca4.fit_transform(wine_std)
wine_pca4[:3]

array([[ 3.31675081, -1.44346263, -0.16573904, -0.21563119],
       [ 2.20946492,  0.33339289, -2.02645737, -0.29135832],
       [ 2.51674015, -1.0311513 ,  0.98281867,  0.72490231]])

In [8]:
pca4.explained_variance_ratio_, sum(pca4.explained_variance_ratio_)

(array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 ]), 0.7359899907589929)

- 6차원

In [9]:
pca6 = PCA(n_components=6)
wine_pca6 = pca6.fit_transform(wine_std)
wine_pca6[:3]

array([[ 3.31675081, -1.44346263, -0.16573904, -0.21563119,  0.69304284,
        -0.22388013],
       [ 2.20946492,  0.33339289, -2.02645737, -0.29135832, -0.25765463,
        -0.92712024],
       [ 2.51674015, -1.0311513 ,  0.98281867,  0.72490231, -0.25103312,
         0.54927605]])

In [10]:
pca6.explained_variance_ratio_, sum(pca6.explained_variance_ratio_)

(array([0.36198848, 0.1920749 , 0.11123631, 0.0706903 , 0.06563294,
        0.04935823]),
 0.8509811607477045)